# Generated by Django 5.1.3 on 2026-09-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_remove_transaction_activity_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="getstartedsection",
            name="button_link",
            field=models.CharField(default="#", max_length=255),
        ),
    ]
