# Generated by Django 6.1 on 2026-09-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='source',
            field=models.CharField(default='deposit', max_length=30),
        ),
    ]
