# Generated by Django 6.1 on 2026-09-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_deposit_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='source',
            field=models.CharField(default='withdrawal', max_length=30),
        ),
    ]
