# Generated by Django 6.1 on 2026-09-20 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_trade_gas_payment_status_trade_payout_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeGasPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT_TRC20', 'USDT TRC20'), ('USDT_ERC20', 'USDT ERC20')], max_length=20)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=18)),
                ('asset_amount', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('proof', models.ImageField(blank=True, null=True, upload_to='trade_gas/proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gas_payment', to='accounts.trade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_gas_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
