# Generated by Django 6.1 on 2026-09-20 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_tradegaspayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='trade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal', to='accounts.trade'),
        ),
    ]
