# Generated by Django 6.1 on 2026-09-20 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_withdrawal_trade'),
        ('core', '0039_alter_getstartedsection_button_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profit',
            options={'ordering': ['-payout_at']},
        ),
        migrations.AddField(
            model_name='profit',
            name='investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profits', to='accounts.investment'),
        ),
        migrations.AddField(
            model_name='profit',
            name='payout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentfeature',
            name='icon',
            field=models.CharField(default='âœ“', max_length=50),
        ),
        migrations.AlterField(
            model_name='profit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='profit',
            constraint=models.UniqueConstraint(fields=('investment', 'payout_at'), name='unique_investment_payout'),
        ),
    ]
